export const products = [
  {
    name: "HP Laptop",
    price: 600,
    image: "https://cnet1.cbsistatic.com/img/XGoLGWy-Ih3pSfXEd1rBJVFbwAQ=/0x0:2667x4000/770x433/2020/08/04/4964745c-5c94-4823-ab62-f40c0c7e38a9/025-hp-envy-17.jpg",
    description: "High performance HP laptop for daily use.",
    category: "Laptop",
    brand: "HP",
    rating: 5,
    numReviews: 11,
    stock: 16,
  },
  {
    name: "Lenovo Laptop",
    price: 580,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeNUClUTkvwZ_UO7FHKRoSwVGl2KwonHNB-A&usqp=CAU",
    description: "Reliable Lenovo laptop for work and study.",
    category: "Laptop",
    brand: "Lenovo",
    rating: 4.5,
    numReviews: 25,
    stock: 20,
  },
  {
    name: "Gaming Mouse",
    price: 350,
    image: "https://picsum.photos/200?1",
    description: "High precision gaming mouse.",
    category: "Computer Accessories",
    brand: "Redgear",
    rating: 3,
    numReviews: 46,
    stock: 2,
  },
  {
    name: "Samsung Monitor",
    price: 270,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhX93oPl7ke3pW30m6Bf8yuVtZXLztiDg4Jw&usqp=CAU",
    description: "Full HD Samsung monitor.",
    category: "Monitor",
    brand: "Samsung",
    rating: 4.5,
    numReviews: 17,
    stock: 9,
  },
  {
    name: "Oppo Mobile",
    price: 300,
    image: "https://picsum.photos/200?2",
    description: "Affordable smartphone with good performance.",
    category: "Mobile & Tablets",
    brand: "Oppo",
    rating: 4,
    numReviews: 33,
    stock: 10,
  },
  {
    name: "Keyboard",
    price: 120,
    image: "https://i.pcmag.com/imagery/roundups/007y4PjTbtgMMDz5SnUq9Em-1.fit_lim.size_1838x.jpg",
    description: "Durable keyboard for office and gaming.",
    category: "Computer Accessories",
    brand: "HP",
    rating: 4,
    numReviews: 20,
    stock: 50,
  },
  {
    name: "Boat Earphones",
    price: 90,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCRrVj0auKueDwvlAc6czV92ee1kkXYjDSGQ&usqp=CAU",
    description: "High quality sound earphones.",
    category: "Earphones",
    brand: "Boat",
    rating: 5,
    numReviews: 14,
    stock: 4,
  },
  {
    name: "Apple Mouse",
    price: 500,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdOnc-l4LAoW_xfugMRR9iUj_6tH4sKpcDgg&usqp=CAU",
    description: "Premium Apple wireless mouse.",
    category: "Computer Accessories",
    brand: "Apple",
    rating: 5,
    numReviews: 180,
    stock: 80,
  },
  {
    name: "Ultrawide Monitor",
    price: 320,
    image: "https://specials-images.forbesimg.com/imageserve/5ede6a4407e58a0007201a40/960x0.jpg",
    description: "Ultra-wide LG monitor for immersive experience.",
    category: "Monitor",
    brand: "LG",
    rating: 4,
    numReviews: 60,
    stock: 14,
  },
  {
    name: "Tiitan Earphone",
    price: 80,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZnLxLWRYFqu5bscSZe09eCmptznpnGfD18w&usqp=CAU",
    description: "Budget friendly earphones.",
    category: "Earphones",
    brand: "Tiitan",
    rating: 5,
    numReviews: 14,
    stock: 160,
  },
];